#ifndef GRINDINGAPP_SRC_OCC_GRINDING_OCC_EXPORT_H_
#define GRINDINGAPP_SRC_OCC_GRINDING_OCC_EXPORT_H_

#include <QtCore/QtGlobal>

#ifdef GRINDING_OCC_BUILDING_DLL
#  define GRINDING_OCC_EXPORT Q_DECL_EXPORT
#else
#  define GRINDING_OCC_EXPORT Q_DECL_IMPORT
#endif

#endif  // GRINDINGAPP_SRC_OCC_GRINDING_OCC_EXPORT_H_
