#ifndef GRINDINGAPP_SRC_KINEMATICS_GRINDING_KINEMATICS_EXPORT_H_
#define GRINDINGAPP_SRC_KINEMATICS_GRINDING_KINEMATICS_EXPORT_H_

#include <QtCore/QtGlobal>

#ifdef GRINDING_KINEMATICS_BUILDING_DLL
#  define GRINDING_KINEMATICS_EXPORT Q_DECL_EXPORT
#else
#  define GRINDING_KINEMATICS_EXPORT Q_DECL_IMPORT
#endif

#endif  // GRINDINGAPP_SRC_KINEMATICS_GRINDING_KINEMATICS_EXPORT_H_
