#ifndef GRINDINGAPP_SRC_UI_GRINDING_UI_EXPORT_H_
#define GRINDINGAPP_SRC_UI_GRINDING_UI_EXPORT_H_

#include <QtCore/QtGlobal>

#ifdef GRINDING_UI_BUILDING_DLL
#  define GRINDING_UI_EXPORT Q_DECL_EXPORT
#else
#  define GRINDING_UI_EXPORT Q_DECL_IMPORT
#endif

#endif  // GRINDINGAPP_SRC_UI_GRINDING_UI_EXPORT_H_
