#ifndef GRINDINGAPP_SRC_UTILS_GRINDING_UTILS_EXPORT_H_
#define GRINDINGAPP_SRC_UTILS_GRINDING_UTILS_EXPORT_H_

#include <QtGlobal>

#ifdef GRINDING_UTILS_BUILDING_DLL
#  define GRINDING_UTILS_EXPORT Q_DECL_EXPORT
#else
#  define GRINDING_UTILS_EXPORT Q_DECL_IMPORT
#endif

#endif  // GRINDINGAPP_SRC_UTILS_GRINDING_UTILS_EXPORT_H_