#ifndef GRINDINGAPP_SRC_GRINDINGAPP_EXPORT_H_
#define GRINDINGAPP_SRC_GRINDINGAPP_EXPORT_H_

// No DLL boundary — export macro is a no-op.
#define GRINDINGAPP_EXPORT

#endif  // GRINDINGAPP_SRC_GRINDINGAPP_EXPORT_H_
