#ifndef GRINDINGAPP_SRC_GRINDINGAPP_EXPORT_H_
#define GRINDINGAPP_SRC_GRINDINGAPP_EXPORT_H_

#include <QtCore/QtGlobal>

#ifdef GRINDINGAPPLIB_EXPORTS
#  define GRINDINGAPP_EXPORT Q_DECL_EXPORT
#else
#  define GRINDINGAPP_EXPORT Q_DECL_IMPORT
#endif

#endif  // GRINDINGAPP_SRC_GRINDINGAPP_EXPORT_H_
