#ifndef GRINDINGAPP_SRC_GRINDING_CORE_EXPORT_H_
#define GRINDINGAPP_SRC_GRINDING_CORE_EXPORT_H_

#include <QtCore/QtGlobal>

#ifdef GRINDING_CORE_BUILDING_DLL
#  define GRINDING_CORE_EXPORT Q_DECL_EXPORT
#else
#  define GRINDING_CORE_EXPORT Q_DECL_IMPORT
#endif

#endif  // GRINDINGAPP_SRC_GRINDING_CORE_EXPORT_H_
